on:
  push:
    branches:
      - master
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.9'
      - run: python -m pip install pipenv
      - run: python -m pipenv install --skip-lock --dev
      # paambaati/codeclimate-action doesn't support major version tag.
      - uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: python -m pipenv run invoke coverage --xml
