name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  check_setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - run: python -m pip install pipenv
      - run: python -m pipenv sync --dev
      - run: python -m pipenv run check_setup
